### ISSUE TITLE
Tweak Parser Algorithm to process iOS WA exported files

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#49] opened 2024-08-24 15:17 UTC
the date format of the export file from WhatsApp iOS is different and the current algorithm throws an error

**Comment by tcouch** [comment] 2024-09-02 11:13
Is this closed by #62 Minor README & languages + parser?

**Comment by MarcosMoreu** [comment] 2024-09-02 11:38
I don't think so as there were other differences in the iOS export file. We need to check properly with iOS and don't have one here. let's keep it open

**Comment by tcouch** [comment] 2024-09-02 13:02
Ok. @acholyn would you be able to paste an export from an iOS whatsapp chat here so we can compare?

**Comment by acholyn** [comment] 2024-09-03 08:40
I can try, shall I fill it with location data?

**Comment by acholyn** [comment] 2024-09-03 08:51
if the locations are just shared from google maps, I also get a different link structure than the ones we've seen

**Comment by acholyn** [comment] 2024-09-03 08:58
[03/09/2024, 9:48:11 AM] Testing export: ‎Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them.
[03/09/2024, 9:48:11 AM] Testing export: ‎You added Testing export

[03/09/2024, 9:48:54 AM] Amanda H: ‎Location: https://maps.google.com/?q=51.593529,-0.167851
[03/09/2024, 9:50:05 AM] Amanda H: Sharing menu opened but link copied
https://maps.app.goo.gl/GV454eY54EYEsL6EA?g_st=ic ‎<This message was edited>
[03/09/2024, 9:52:03 AM] Amanda H: Link copied and pasted

https://maps.app.goo.gl/q8mwtVGfhLptgDVA7?g_st=com.google.maps.preview.copy ‎<This message was edited>
[03/09/2024, 9:52:32 AM] Amanda H: Direct share to this chat
https://maps.app.goo.gl/q8mwtVGfhLptgDVA7?g_st=iw ‎<This message was edited>
[03/09/2024, 9:52:47 AM] Amanda H: ‎You deleted this message.
[03/09/2024, 9:52:53 AM] Amanda H: ‎You deleted this message.
[03/09/2024, 9:53:29 AM] Amanda H: ‎You deleted this message.
[03/09/2024, 9:54:19 AM] Amanda H: WhatsApp selected and then chat chosen
https://maps.app.goo.gl/wSps8jnohzFjbt6H6?g_st=iw

**Comment by MarcosMoreu** [comment] 2024-09-03 09:15
Yes the locations need to be shared only from within WA to get a url with latitute and longitude

**Comment by acholyn** [comment] 2024-09-04 09:32
For coordinates (at least on iPhone) the location needs to be through current location or a dropped pin, not a selected place. Format will the same as on Android, differences based on the user's date-time format - on iPhone this is surrounded by `[ ]`

**Comment by MarcosMoreu** [comment] 2024-09-04 09:57
Also in Android, the location needs to be shared using "Share your current Location", not by selecting a place, otherwise the format is (i.e. without lat/lng)

04/09/2024, 12:52 - Marcos: NLM Kappelet
https://foursquare.com/v/4ef5babe9911b01dda209b76
04/09/2024, 12:52 - Marcos: testing

**Comment by tcouch** [comment] 2024-09-09 10:04
Let's keep this open until #74 is done so we can confirm things are working as expected on iPhone more easily.

**Comment by acholyn** [comment] 2024-09-09 14:53
ah - the IOS one also has more granularity on the time, showing ms

**Comment by acholyn** [comment] 2024-09-10 12:04
Unsure why, but this regex for the ios format doesn't work on the app but it works with regex101.com
```
console.log("ios format");
// iOS format
messageRegex =
/\[(\d{2}\/\d{2}\/\d{4}),\s(\d{1,2}:\d{2}:\d{2}\s(?:AM|PM))\]\s(.*?):\s((.|\n)*?)(?=\n\[|$)/g;
```
<img width="146" alt="image" src="https://github.com/user-attachments/assets/9c5c6f0a-c147-4442-9f06-b7cb53702551">

<img width="664" alt="image" src="https://github.com/user-attachments/assets/18161da1-5021-40be-8cb8-d6d4a4ca3789">


putting this here for a papertrail

**Comment by tcouch** [comment] 2024-09-17 15:19
I encountered a similar issue where the regex worked on regex101, but not on the app. The cause was the global `/g` flag at the end of the regex in my case. It was something to do with the search position index not getting reset? Anyway, does removing that flag fix it?

**Closed** 2024-09-18 09:59 UTC
